name: 'Simple Icons Release'
description: 'Automatic releases for Simple Icons'
author: 'Eric Cornelissen'

inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true

runs:
  using: 'node20'
  main: 'lib/index.mjs'
